# Generated by Django 5.1.6 on 2025-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_class', models.CharField(max_length=100)),
                ('subclass', models.CharField(max_length=100)),
                ('example_alloy', models.CharField(max_length=100)),
                ('chemical_composition', models.TextField()),
                ('laser_power', models.FloatField()),
                ('scan_speed', models.FloatField()),
                ('beam_spot', models.CharField(max_length=100)),
                ('beam_quality', models.FloatField()),
                ('surface_material', models.CharField(max_length=100)),
                ('pre_treatment', models.CharField(max_length=100)),
                ('temp_range', models.CharField(max_length=50)),
                ('surface_hardness', models.FloatField()),
                ('hardened_layer_depth', models.FloatField()),
                ('residual_stresses', models.CharField(max_length=100)),
                ('wear_resistance', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
