# Generated by Django 5.1.6 on 2025-05-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metal_Class', models.CharField(default='From Excel', max_length=255)),
                ('Subclass', models.CharField(default='From Excel', max_length=255)),
                ('Example_Alloy', models.CharField(default='From Excel', max_length=255)),
                ('Chemical_Composition', models.TextField(default='From Excel')),
                ('Laser_Power_W', models.FloatField(default=0.0)),
                ('Scanning_Speed_mm_s', models.FloatField(default=0.0)),
                ('Beam_Spot_Size_and_Profile', models.CharField(default='From Excel', max_length=255)),
                ('Beam_Quality_M2', models.FloatField(default=0.0)),
                ('Surface_Material', models.CharField(default='From Excel', max_length=255)),
                ('Pre_treatment', models.CharField(default='From Excel', max_length=255)),
                ('Temperature_Range_C', models.IntegerField(default=0)),
                ('Surface_Hardness_HV', models.IntegerField(default=0)),
                ('Hardened_Layer_Depth_mm', models.FloatField(default=0.0)),
                ('Residual_Stresses', models.CharField(default='From Excel', max_length=255)),
                ('Wear_Resistance', models.CharField(default='From Excel', max_length=255)),
                ('Source', models.CharField(default='From Excel', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
